# Generated by Django 4.0.5 on 2022-06-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='clm_name',
        ),
    ]
