# Generated by Django 4.0.5 on 2022-06-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_rename_name_column_clm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
