# Generated by Django 4.0.4 on 2022-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
